[tool.poetry]
name = "rcx-tk"
version = "0.3.0"
description = "This package adjusts and cleans the metadata file provided by a user."
authors = [
    "Zargham Ahmad <zargham.ahmad@recetox.muni.cz>" ,
    "Kristina Gomoryova <kristina.gomoryova@recetox.muni.cz>",
    "Helge Hecht <helge.hecht@recetox.muni.cz>"
]
license = "MIT"
readme = "README.md"
keywords = ["metadata", "alkanes", "metabolomics"]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^3.0.3"
pandas-stubs = "^3.0.0.260204"
click = "^8.1.7"
openpyxl = "^3.1.5"

[tool.poetry.group.dev.dependencies]
build = "^1.5.0"
coverage = "^7.14.0"
pytest = ">=8.2.2,<10.0.0"
pytest-cov = "^5.0.0"
ruff = "^0.15.12"
myst-parser = "^5.0.0"
twine = "^6.2.0"
wheel = "^0.47.0"
sphinx = "^8.2.3"
sphinx-autoapi = "^3.1.1"
sphinx-rtd-theme = "^3.1.0"
cffconvert = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 120

# Enable Pyflakes `E` and `F` codes by default.
lint.select = [
    "F",  # Pyflakes
    "E",  # pycodestyle (error)
    "W",    # pycodestyle (warning)
    # "C90",  # mccabe
    "I",    # isort
    "D",    # pydocstyle
    # "PL",   # Pylint
    # "PLC",  # Convention
    # "PLE",  # Error
    # "PLR",  # Refactor
    # "PLW",  # Warning

]
lint.ignore = [
    'D100',  # Missing module docstring
    'D104',  # Missing public package docstring
    # The following list excludes rules irrelevant to the Google style
    'D203',
    'D204',
    'D213',
    'D215',
    'D400',
    'D401',
    'D404',
    'D406',
    'D407',
    'D408',
    'D409',
    'D413',
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["A", "B", "C", "D", "E", "F", "I"]
lint.unfixable = []

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    ".venv",
    "scripts",
]

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Tests can ignore a few extra rules
"tests/**.py" = [
    "ANN201", # Missing return type annotation for public function
    "PT011",  # Missing `match` parameter in `pytest.raises()`
    "S101",   # Use of assert is detected
    "D103"    # Missing docstring in public function
]

[tool.ruff.lint.isort]
known-first-party = ["rcx_tk"]
force-single-line = true
no-lines-before = ["future","standard-library","third-party","first-party","local-folder"]

[tool.poetry.scripts]
rcx_tk = "rcx_tk.__main__:main"
rcx-tk = "rcx_tk.__main__:main"


[tool.bumpversion]
current_version = "0.3.0"

[[tool.bumpversion.files]]
filename = "src/rcx_tk/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "CITATION.cff"

[[tool.bumpversion.files]]
filename = "docs/conf.py"