name: documentation

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --with dev
      - name: Install pandoc using apt
        run: sudo apt install pandoc
      - name: Build documentation
        run: make coverage doctest html
        working-directory: docs